### PR TITLE
Set the lint working dir to the package dir

### LINKED ISSUE #10: "Cannot find module 'eslint-config-xo-react'"
If I try to use `eslint-config-xo-react` the linter complains it can't load the module.

The stack trace goes through `~/.atom`, I assume it's not trying the node_modules of the project. From the command line, xo works fine.

Am I missing some configuration?

package.json:
```
  "devDependencies": {
    "eslint": "^1.9.0",
    "eslint-config-xo-react": "^0.3.0",
    "eslint-plugin-react": "^3.9.0",
    "xo": "^0.11.1"
  },
  "xo": {
    "esnext": true,
    "semicolon": false,
    "env": [
      "browser",
      "mocha",
      "webpack"
    ],
    "extends": "eslint-config-xo-react"
  },
```

### PR DESCRIPTION
**Pull request by wmertens**
ESLint needs the cwd to be the package root in order to find the installed eslint plugins

Fixes #10

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -13,12 +13,19 @@ function lint(textEditor) {
 	const filePath = textEditor.getPath();
 	let report;
 
+	let dir = path.dirname(filePath);
+	let lastDir = '';
+	while (dir !== lastDir && !fs.existsSync(path.join('package.json'))) {
+		lastDir = dir;
+		dir = path.resolve(dir, '..');
+	}
```
Comment (sindresorhus) [inline index.js]: Just use https://github.com/sindresorhus/pkg-dir

**Comment by wmertens** [comment]
@sindresorhus ^

**Comment by sindresorhus** [comment]
> I wonder if I should memoize the result, probably not worth it.

Nah, not worth it.

**Comment by sindresorhus** [comment]
Looks good. Thanks :)
