### PR TITLE
Add `Fix on Save` option

### LINKED ISSUE #44: Fix on save
I saw in #7 that you chose not to add "fix on save". I think it would be a nice addition, any reason for not adding it?

### PR DESCRIPTION
**Pull request by AntonNiklasson**
I added a config option for enabling fixing errors and warnings on save.

Thoughts?

---

Fixes #44

### CODE REVIEW

**Comment by AntonNiklasson** [comment]
Should the fix only run if `xo` is a dependancy, [just like the lint](https://github.com/AntonNiklasson/atom-linter-xo/blob/59793fb958d82fbfe89a4324d11eb5432b253f33/index.js#L44)?

**Comment by sindresorhus** [comment]
Yes

File: index.js [hunk 1]
```diff
@@ -108,31 +133,28 @@ export function activate() {
...
-			const output = report.results[0].output;
+	atom.workspace.observeTextEditors(editor => {
+		editor.getBuffer().onWillSave(() => {
+			const isJS = SUPPORTED_SCOPES.includes(editor.getGrammar().scopeName);
+			const shouldFixOnSave = atom.config.get('linter-xo.fixOnSave');
 
-			if (output) {
-				setText(output);
+			if (isJS && shouldFixOnSave) {
+				fix();
```
Comment (sindresorhus) [inline index.js]: Pass `editor` to `fix()` instead of getting the active editor inside the `fix` function. You also have to change line `136` to a function that get's the active editor.

File: index.js [hunk 2]
```diff
@@ -108,31 +133,28 @@ export function activate() {
...
-
-			let report;
-
-			allowUnsafeNewFunction(() => {
-				report = lintText(editor.getText(), {
-					fix: true,
-					cwd: path.dirname(editor.getPath())
-				});
-			});
+		'XO:Fix': fix
```
Comment (sindresorhus) [inline index.js]:
```js
'XO:Fix': editor => {
    fix(atom.workspace.getActiveTextEditor());
};

File: index.js [hunk 3]
```diff
@@ -108,31 +133,28 @@ export function activate() {
...
+	}));
 
-			const output = report.results[0].output;
+	atom.workspace.observeTextEditors(editor => {
```
Comment (sindresorhus) [inline index.js]: I think you need to wrap this in `this.subscriptions.add(`.

**Comment by sindresorhus** [comment]
Generally looks :)

Also needs some docs.

**Comment by AntonNiklasson** [comment]
Tanks for the feedback, Sindre. I'll update the PR as soon as I have time.

**Comment by AntonNiklasson** [comment]
I extracted the package lookup to share it between `lint` and `fix`.

Perhaps it would be nice to be able to run `XO:Fix` on any code without a `package.json` present, but that might out of the scope of this PR.

**Comment by sindresorhus** [comment]
> Perhaps it would be nice to be able to run XO:Fix on any code without a package.json present, but that is probably out of scope for this PR.

That was already possible before this PR and should be preserved. Running `XO: Fix` is an explicit action and the user should be allowed to do it on any kind of project, even one without XO.

File: index.js [hunk 4]
```diff
@@ -89,14 +100,34 @@ function lint(textEditor) {
 	});
 }
 
+function fix(editor) {
+	const filePath = editor.getPath();
+	const {pkg} = findPkg(pkgDir.sync(path.dirname(filePath)));
+
+	if (!editor || !xoInPkg(pkg)) {
```
Comment (sindresorhus) [inline index.js]: This is incorrect and inefficient. When the `editor` does not exist it will fail on line 104, as it tries to get `.getPath()` of `undefined`. There's also no point in running `findPkg` when `editor` does not exist. The editor if-statement should be at the top.

File: index.js [hunk 5]
```diff
@@ -108,31 +139,31 @@ export function activate() {
...
+		'XO:Fix': () => fix(atom.workspace.getActiveTextEditor())
+	}));
 
-			let report;
+	this.subscriptions.add(
+		atom.workspace.observeTextEditors(editor => {
+			editor.getBuffer().onWillSave(() => {
+				const isJS = SUPPORTED_SCOPES.includes(editor.getGrammar().scopeName);
+				const shouldFixOnSave = atom.config.get('linter-xo.fixOnSave');
+				const dependsOnXO = true;
```
Comment (sindresorhus) [inline index.js]: ?

File: index.js [hunk 6]
```diff
@@ -29,26 +34,32 @@ function lint(textEditor) {
...
+	if (currentDir === null) {
 		return [];
 	}
 
-	// only lint when `xo` is a dependency
-	if (!(pkg.dependencies && pkg.dependencies.xo) &&
-		!(pkg.devDependencies && pkg.devDependencies.xo)) {
+	const {pkg, rootDir} = findPkg(currentDir);
+
+	if (!rootDir || rootDir === null || !xoInPkg(pkg)) {
```
Comment (sindresorhus) [inline index.js]: Why are you doing both `!rootDir` and `rootDir === null`? Seems like the latter should be enough.

**Comment by AntonNiklasson** [comment]
Sorry for that messy commit. Hopefully this last one gets it right.

**Comment by sindresorhus** [comment]
Awesome! Thank you for working on this @AntonNiklasson :)

**Comment by AntonNiklasson** [comment]
Well thank you for helping me! This was my first open-source PR! :)
